"""Backend-neutral vector storage and service-composed graph retrieval."""

from .graph import GraphTableNames, build_graph_registry, with_graph_tables
from .models import (
    BackendCapabilities,
    BackendConfig,
    BackendRequirements,
    FieldSpec,
    FieldType,
    FilterExpression,
    FilterGroup,
    GraphDirection,
    GraphEdge,
    GraphNode,
    GraphNodeRef,
    GraphPath,
    GraphSort,
    GraphStep,
    GraphTraversalQuery,
    GraphTraversalResult,
    IndexKind,
    IndexSpec,
    Page,
    Predicate,
    Record,
    RecordQuery,
    Sort,
    SparseVector,
    TableSpec,
    TraversedGraphEdge,
    VectorFieldSpec,
    VectorHit,
    VectorQuery,
    VectorValue,
    scope_predicates,
)
from .registry import BackendRegistry, TableRegistry
from .scope import DatabaseScope, ScopeValue
from .service import VectorDBService
from .vector_store import ScopedVectorStore

__all__ = [
    "BackendCapabilities",
    "BackendConfig",
    "BackendRegistry",
    "BackendRequirements",
    "DatabaseScope",
    "FieldSpec",
    "FieldType",
    "FilterExpression",
    "FilterGroup",
    "GraphDirection",
    "GraphEdge",
    "GraphNode",
    "GraphNodeRef",
    "GraphPath",
    "GraphSort",
    "GraphStep",
    "GraphTableNames",
    "GraphTraversalQuery",
    "GraphTraversalResult",
    "IndexKind",
    "IndexSpec",
    "Page",
    "Predicate",
    "Record",
    "RecordQuery",
    "ScopeValue",
    "ScopedVectorStore",
    "Sort",
    "SparseVector",
    "TableRegistry",
    "TableSpec",
    "TraversedGraphEdge",
    "VectorDBService",
    "VectorFieldSpec",
    "VectorHit",
    "VectorQuery",
    "VectorValue",
    "build_graph_registry",
    "scope_predicates",
    "with_graph_tables",
]
