"""SDK-side skill management primitives."""

from ..errors import SkillBundleError
from .async_client import AsyncSkillClient
from .backends import AsyncSkillBackend, HttpSkillBackend, InMemorySkillBackend
from .bundle import (
    CONTENT_HASH_ALGORITHM,
    SKILL_WHITELIST,
    bundle_files_from_content,
    compute_content_hash,
    deserialize_bundle,
    is_whitelisted,
    normalize_bundle,
    read_local_bundle,
    resolve_skill_dir,
    serialize_bundle,
)
from .cloud import SkillCloudClient
from .detector import detect_skill_context
from .history import SkillHistoryStore
from .installer import SkillInstaller
from .local_repository import LocalSkillRepository
from .manager import SkillManager, SkillRegisterPlan
from .models import (
    CloudSkillsPage,
    CloudSkillSummary,
    DuplicateSkillAction,
    DuplicateSkillMatch,
    EvolveCloudRequest,
    EvolveCloudResult,
    ExportSkillRequest,
    ExportSkillResult,
    HashState,
    LocalSkillFileEntry,
    LocalSkillFileRole,
    LocalSkillManifest,
    LocalSkillOperationStatus,
    LocalSkillOperationType,
    LocalSkillSnapshot,
    LocalSkillSyncState,
    LocalSkillVersion,
    LocalSkillVersionFiles,
    LocalSkillVersionMetadata,
    LocalSyncOperation,
    LocalSyncOutbox,
    PromoteCloudRequest,
    PromoteCloudResult,
    PublishLocalRequest,
    PublishLocalResult,
    PullVersionContent,
    PullVersionsPage,
    PullVersionSummary,
    PushVersionRequest,
    PushVersionResult,
    RegisterLocalRequest,
    RegisterLocalResult,
    RollbackPlan,
    SkillCheckoutPlan,
    SkillContentData,
    SkillContext,
    SkillDiffResult,
    SkillEvolveData,
    SkillEvolveMode,
    SkillFlushResult,
    SkillListData,
    SkillOrigin,
    SkillPendingUpload,
    SkillPendingUploadsFile,
    SkillRecord,
    SkillRegisterData,
    SkillSummary,
    SkillSyncData,
    SkillSyncRequestItem,
    SkillSyncResult,
    SkillUpdatePlan,
    SkillUsage,
    SkillVersion,
    SkillVersionsData,
    SkillVersionStatus,
    SyncCloudItem,
    SyncCloudRequest,
    SyncCloudResult,
    SyncCloudResultItem,
)
from .pending import SkillPendingUploadStore
from .registry import SkillRegistry
from .snapshot import compute_local_snapshot_hash, read_local_snapshot, snapshot_from_editor

__all__ = [
    "CONTENT_HASH_ALGORITHM",
    "SKILL_WHITELIST",
    "CloudSkillSummary",
    "CloudSkillsPage",
    "AsyncSkillClient",
    "AsyncSkillBackend",
    "HttpSkillBackend",
    "InMemorySkillBackend",
    "DuplicateSkillAction",
    "DuplicateSkillMatch",
    "EvolveCloudRequest",
    "EvolveCloudResult",
    "ExportSkillRequest",
    "ExportSkillResult",
    "HashState",
    "LocalSkillFileEntry",
    "LocalSkillFileRole",
    "LocalSkillManifest",
    "LocalSkillOperationStatus",
    "LocalSkillOperationType",
    "LocalSkillRepository",
    "LocalSkillSnapshot",
    "LocalSkillSyncState",
    "LocalSkillVersionFiles",
    "LocalSkillVersionMetadata",
    "LocalSyncOperation",
    "LocalSyncOutbox",
    "LocalSkillVersion",
    "PublishLocalRequest",
    "PublishLocalResult",
    "PromoteCloudRequest",
    "PromoteCloudResult",
    "PullVersionContent",
    "PullVersionSummary",
    "PullVersionsPage",
    "PushVersionRequest",
    "PushVersionResult",
    "RegisterLocalRequest",
    "RegisterLocalResult",
    "RollbackPlan",
    "SkillContext",
    "SkillBundleError",
    "SkillCheckoutPlan",
    "SkillCloudClient",
    "SkillContentData",
    "SkillEvolveData",
    "SkillEvolveMode",
    "SkillFlushResult",
    "SkillDiffResult",
    "SkillHistoryStore",
    "SkillInstaller",
    "SkillListData",
    "SkillManager",
    "SkillOrigin",
    "SkillPendingUpload",
    "SkillPendingUploadStore",
    "SkillPendingUploadsFile",
    "SkillRegisterData",
    "SkillRegisterPlan",
    "SkillRecord",
    "SkillRegistry",
    "SkillSummary",
    "SkillSyncData",
    "SkillSyncRequestItem",
    "SkillSyncResult",
    "SkillUpdatePlan",
    "SkillUsage",
    "SkillVersion",
    "SkillVersionStatus",
    "SkillVersionsData",
    "SyncCloudItem",
    "SyncCloudRequest",
    "SyncCloudResult",
    "SyncCloudResultItem",
    "bundle_files_from_content",
    "compute_content_hash",
    "compute_local_snapshot_hash",
    "detect_skill_context",
    "deserialize_bundle",
    "is_whitelisted",
    "normalize_bundle",
    "read_local_bundle",
    "read_local_snapshot",
    "resolve_skill_dir",
    "serialize_bundle",
    "snapshot_from_editor",
]
